
// This file has been generated by the GUI designer. Do not modify.
namespace RecordingCosts
{
	public partial class DisplayDaysWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.TextView textview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RecordingCosts.DisplayDaysWindow
			this.Name = "RecordingCosts.DisplayDaysWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("DisplayDaysWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child RecordingCosts.DisplayDaysWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.vbox1.Add(this.textview1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.textview1]));
			w1.Position = 0;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
