
// This file has been generated by the GUI designer. Do not modify.
namespace RecordingCosts
{
	public partial class SelectDays
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView daysRecTxtView;

		private global::Gtk.SpinButton spinbutton1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button OK1;

		private global::Gtk.Button Cancel1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RecordingCosts.SelectDays
			this.Name = "RecordingCosts.SelectDays";
			this.Title = global::Mono.Unix.Catalog.GetString("SelectDays");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child RecordingCosts.SelectDays.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.daysRecTxtView = new global::Gtk.TextView();
			this.daysRecTxtView.Buffer.Text = "How many days recording?";
			this.daysRecTxtView.CanFocus = true;
			this.daysRecTxtView.Name = "daysRecTxtView";
			this.daysRecTxtView.Editable = false;
			this.daysRecTxtView.CursorVisible = false;
			this.GtkScrolledWindow.Add(this.daysRecTxtView);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.spinbutton1 = new global::Gtk.SpinButton(0, 100, 1);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10;
			this.spinbutton1.ClimbRate = 1;
			this.spinbutton1.Numeric = true;
			this.spinbutton1.Value = 1;
			this.vbox2.Add(this.spinbutton1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.spinbutton1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.OK1 = new global::Gtk.Button();
			this.OK1.CanFocus = true;
			this.OK1.Name = "OK1";
			this.OK1.UseUnderline = true;
			this.OK1.Label = global::Mono.Unix.Catalog.GetString("OK");
			this.hbox1.Add(this.OK1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.OK1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.Cancel1 = new global::Gtk.Button();
			this.Cancel1.CanFocus = true;
			this.Cancel1.Name = "Cancel1";
			this.Cancel1.UseUnderline = true;
			this.Cancel1.Label = global::Mono.Unix.Catalog.GetString("Cancel");
			this.hbox1.Add(this.Cancel1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Cancel1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 169;
			this.DefaultHeight = 134;
			this.Show();
			this.OK1.Clicked += new global::System.EventHandler(this.OnOKClick);
		}
	}
}
