
// This file has been generated by the GUI designer. Do not modify.
namespace RecordingCosts
{
	public partial class SessionSelectorWidget
	{
		private global::Gtk.HBox hbox3;

		private global::Gtk.CheckButton amcheck;

		private global::Gtk.CheckButton pmcheck;

		private global::Gtk.CheckButton evecheck;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RecordingCosts.SessionSelectorWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "RecordingCosts.SessionSelectorWidget";
			// Container child RecordingCosts.SessionSelectorWidget.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.amcheck = new global::Gtk.CheckButton();
			this.amcheck.CanFocus = true;
			this.amcheck.Name = "amcheck";
			this.amcheck.Label = global::Mono.Unix.Catalog.GetString("AM");
			this.amcheck.DrawIndicator = true;
			this.amcheck.UseUnderline = true;
			this.hbox3.Add(this.amcheck);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.amcheck]));
			w1.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.pmcheck = new global::Gtk.CheckButton();
			this.pmcheck.CanFocus = true;
			this.pmcheck.Name = "pmcheck";
			this.pmcheck.Label = global::Mono.Unix.Catalog.GetString("PM");
			this.pmcheck.DrawIndicator = true;
			this.pmcheck.UseUnderline = true;
			this.hbox3.Add(this.pmcheck);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.pmcheck]));
			w2.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.evecheck = new global::Gtk.CheckButton();
			this.evecheck.CanFocus = true;
			this.evecheck.Name = "evecheck";
			this.evecheck.Label = global::Mono.Unix.Catalog.GetString("Evening");
			this.evecheck.DrawIndicator = true;
			this.evecheck.UseUnderline = true;
			this.hbox3.Add(this.evecheck);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.evecheck]));
			w3.Position = 2;
			this.Add(this.hbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
